# Generated by Django 4.0.4 on 2022-06-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescripcion',
            name='dosis',
        ),
        migrations.AlterField(
            model_name='prescripcion',
            name='frecuencia',
            field=models.CharField(default='', max_length=50),
        ),
    ]
