# Generated by Django 4.0.4 on 2022-06-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0002_remove_prescripcion_dosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='dosis',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='id_medicamento',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='stock',
            field=models.IntegerField(blank=True),
        ),
    ]
