# Generated by Django 4.0.4 on 2022-06-22 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0003_alter_medicamento_dosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='rut',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
